name: Build and Release hello-react

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Archive build output
        run: |
          cd build
          zip -r ../hello-react-build.zip .
          cd ..

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: hello-react-build
          path: hello-react-build.zip
  
  release-artifacts:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Commit SHA
        id: extract_sha
        run: |
          echo "short_sha=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0-${{ env.short_sha }}
          release_name: r1.0.0-${{ env.short_sha }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_TRIGGER_ACTION }}

      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: hello-react-build
          path: .

      - name: Upload build output as release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./hello-react-build.zip
          asset_name: hello-react-build-${{ env.short_sha }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_TRIGGER_ACTION }}
  
  trigger-infra-and-deployment:
    needs: release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Infra Pipeline
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: suchayanchatterjee/hello-azure
          event-type: react-app-publish-success
          token: ${{ secrets.GH_TOKEN_TRIGGER_ACTION }}