name: Build and Release hello-react

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build
  
  release-artifacts:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Extract Commit SHA
        id: extract_sha
        run: |
          echo "short_sha=$(echo $GITHUB_SHA | cut -c1-5)" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0-${{ env.short_sha }}
          release_name: Build ${{ env.short_sha }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_TRIGGER_ACTION }}
  
  trigger-infra-and-deployment:
    needs: release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Infra Pipeline
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: suchayanchatterjee/hello-azure
          event-type: react-app-publish-success
          token: ${{ secrets.GH_TOKEN_TRIGGER_ACTION }}